#!/bin/bash
echo "Verificando AAB para Play Store..."
echo "Arquivo: ./amigomontador-release.aab"
echo "Tamanho: $(du -h ./amigomontador-release.aab | cut -f1)"
echo "Tipo: $(file ./amigomontador-release.aab)"
echo ""
echo "Checklist para Play Store:"
echo "✓ Arquivo AAB gerado"
echo "✓ Keystore configurado"
echo "✓ Versão 1.0 definida"
echo "✓ Package name: com.amigomontador.app"
echo ""
echo "Próximos passos:"
echo "1. Upload do AAB na Play Console"
echo "2. Configurar metadados da app"
echo "3. Adicionar screenshots"
echo "4. Submeter para revisão"
